project:
  title: "computo_pishchagina_changepoints"
  render:
    - main.qmd
    - README.qmd
status: published

title: "Geometric-Based Pruning Rules for Change Point Detection in Multiple Independent Time Series"
author:
  - name: Liudmila Pishchagina
    corresponding: true
    email: liudmila.pishchagina@univ-evry.fr
    url: https://github.com/lpishchagina
    affiliations:
      - name: Université Paris-Saclay, CNRS, Université d'Évry-Val-d'Essonne, Laboratoire de Mathématiques et Modélisation d'Évry, France
  - name: Guillem Rigaill
    email: guillem.rigaill@inrae.fr
    orcid: 0000-0002-7176-7511
    affiliations:
      - name: Université Paris-Saclay, CNRS, Université d'Évry-Val-d'Essonne, Laboratoire de Mathématiques et Modélisation d'Évry, France
      - name: Université Paris-Saclay, CNRS, INRAE, Université d'Évry-Val-d'Essonne, Institute of Plant Sciences Paris-Saclay (IPS2), Orsay, France
  - name: Vincent Runge
    orcid: 0000-0002-4857-1799
    email: vincent.runge@univ-evry.fr
    affiliations:
      - name: Université Paris-Saclay, CNRS, Université d'Évry-Val-d'Essonne, Laboratoire de Mathématiques et Modélisation d'Évry, France
date: 07/12/2024
abstract: >+
 We address the challenge of identifying multiple change points in a group of independent time series, assuming these change points occur simultaneously in all series and their number is unknown. The search for the best segmentation can be expressed as a minimization problem over a given cost function. We focus on dynamic programming algorithms that solve this problem exactly. When the number of changes is proportional to data length, an inequality-based pruning rule encoded in the PELT algorithm leads to a linear time complexity. Another type of pruning, called functional pruning, gives a close-to-linear time complexity whatever the number of changes, but only for the analysis of univariate time series. We propose a few extensions of functional pruning for multiple independent time series based on the use of simple geometric shapes (balls and hyperrectangles). We focus on the Gaussian case, but some of our rules can be easily extended to the exponential family. In a simulation study we compare the computational efficiency of different geometric-based pruning rules. We show that for a small number of time series some of them ran significantly faster than inequality-based approaches in particular when the underlying number of changes is small compared to the data length.
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/9vvx-eq57"
  publisher: "French Statistical Society"
  issn: "2824-7795"
  url: "https://computo-journal.org/published-202406-pishchagina-change-point/"
related-identifiers:
  - relation: IsVersionOf
    type: arXiv
    identifier: "2306.09555"
github-user: computorg
repo: "published-202406-pishchagina-change-point"
